---
title: Who's NaCNO?
menu:
  main:
    name: Who am I?
    weight: 98
    params:
      icon: copyright
toc: false
description: hello, it me!
math: false
---

* the ∞-catgirl & witch apprentice

As of June 2026, this blog is run by *Roxanne Huang* (she/they) (see below for more on names),
which is me, a graduate student in mathematics at FU Berlin in the working group of Prof. Holger Reich,
trying to work her way into homotopy theory and/or algebraic K-theory.
I'm particularly interested in chromatic structures, equivariant and motivic homotopy theory.

I enjoy reinterpreting and explaining well-known things,
as I slowly work towards the point where I'm able to produce something original.

** Names
- My name is *Roxanne Huang*, also formally *Ruochong Huang*.
- The blog is also run under the name *NaCNO*, a stylisation of a Japanese name *なつの*.
  The letter C therefore denotes a syllable ​/tsɯ/ and not ​the consonant /k/.

* what's around?
some of the stuff I've worked on or am working on.
at the moment, I'm mostly writing short math notes in the form of blog posts,
as well as some little tips in setting up my working linux environment.
other things which are important to my life may also appear in the near future.

* any feedback, suggestion or comment?
Feel free to open an issue or discussion on GitHub!
