---
title: Adams spectral sequence on bounded below spectra
date: 2026-02-17T22:20:39+01:00
draft: false
math: true
toc: true
tags:
  - Math
  - Homotopy
description: Finally had an argument that I'm happy with
---
#+OPTIONS: tex:verbatim
I've learned most techniques from Mathew--Naumann--Noel's Nilpotence and Descent paper [ND], as well
as a central but mundane trick from Nikolaus--Scholze's Topological Cyclic Homology paper [TC]. Although the Adams spectral sequence
is no stranger for the mathematical omnivore I have been, I've always assumed to some extent that they
/do what they claim to/, and somewhat focused on what the machine produces, less so on what it computes.

References:
1. [ND]: [[https://arxiv.org/abs/1507.06869][Nilpotence and descent in equivariant stable homotopy theory]] by Akhil Mathew, Niko Naumann and Justin Noel
2. [TC]: [[http://arxiv.org/abs/1707.01799][On topological cyclic homology]] by Thomas Nikolaus and Peter Scholze

For our purpose today, the Adams spectral sequence is the totalisation spectral sequence associated to an \(\mathbb{E}_1\)-ring
spectrum \(E\) and a spectrum \(X\). The major examples we'd like to have in mind are \(E = \mathbb{F}_p\) and \(\mathrm{MU}\).
Other common examples include Bott-periodic or connective topological \(\mathrm{K}\)-theory \(\mathrm{KU}\), \(\mathrm{ku}\), as well as Morava \(\mathrm{E}\)-theories.
A well-known result (Devinatz--Hopkins cites Morava's change of rings theorem.) identifies the \(K(n)\)-local \(E_n\)-Adams spectral sequence with the
homotopy fixed points spectral sequence for the Morava stabiliser group. We will not concern ourselves with these (extremely interesting) examples.

The situation we concern ourselves with in the current blog post is classical: When \(E\) is connective and \(\mathbb{S} \to E\) is surjective on \(\pi_0\).
(A similar statement exists for \(\mathbb{Z} \subseteq \pi_0 E \subseteq \mathbb{Q}\) where the method employed here doesn't directly apply.)
#+BEGIN_QUOTE
When \(E\) is a connective \(\mathbb{E}_1\)-ring whose unit morphism \(\mathbb{S} \to E\) is surjective on \(\pi_0\) and \(X\) is a bounded below spectrum,
the \(E\)-descent object \(D_E X\) (in \(\mathrm{Sp}\)) for \(X\) (defined below) coincides with the Bousfield localisation of \(X\) at the Moore
spectrum associated to \(\pi_0 E\).
#+END_QUOTE
For instance, if \(X\) is connective then \(D_{\mathrm{MU}} X \simeq X\) and \(D_{\mathbb{F}_p} X \simeq X_{\hat p}\) is the \(p\)-completion. This
justifies the classical case of Adams(-Novikov) spectral sequences.

#+BEGIN_QUOTE
The connectivity is crucial, both on \(E\) and on \(X\). At a fixed prime, the Morava \(K\)-theories are \(p\)-complete and mutually acyclic.
#+END_QUOTE

* The descent tower and the Adams tower
This section is closely following, if not taken from, [ND, Sec. 2.1].

#+BEGIN_QUOTE
For a spectrum \(X\), define /its/ *\(E\)-descent diagram* \(D^\bullet_E X \coloneqq X \otimes E^{\otimes (1 + \bullet)}\) to be
the (coaugmented) cosimplicial spectrum with face maps given by inserting units and degeneracies by multiplication of \(E\) (and constant on \(X\)).
The *total \(E\)-descent object* of \(X\) is the totalisation
\[
D_E X \coloneqq \lim_{\bullet : \Delta} D^\bullet_E X,
\]
which comes along with the coskeletal filtration \(D_E X \simeq \lim_{-1 \leq n \to \infty} D^{(n)}_E X\), where
\[
D^{(n)}_E X \coloneqq \lim_{\bullet : \Delta_{\leq n}} X \otimes D^\bullet_E.
\]
We call this the *descent tower*. The associated spectral sequence is called the *Adams spectral sequence*.
#+END_QUOTE
We use the only reasonable convention that \(\Delta_{\leq -1}=\emptyset\). A few remarks are due (All can be found in [ND] in a generalised setting):

2. There is a natural map \(X \to D_E X\) induced by the coaugmentation, which we claimed and will know to be a localisation in the classical situation.
   However we might like this to be true, a priori the descent construction \(D_E(-)\) has no reason to be idempotent, let alone a localisation.
3. If \(X\) has a right \(E\)-module structure, then the coaugmented cosimplicial object \(X \otimes D^\bullet_E\) has an extra degeneracy,
   and is hence a universal limit diagram. In this case, the map \(X \to D_E X\) is an isomorphism.
   This property propagates to the idempotent complete stable subcategory generated by \(E\)-modules.
4. Consequently, if \(E\) is a finite \(E_1\)-ring spectrum, so that \(E \otimes -\) commutes
   with limits, we have that \(X \to D_E X\) is an \(E\)-equivalence into an \(E\)-local spectrum.
   The descent object thus coincides with the Bousfield \(E\)-localisation functor.
   Typical examples include the endomorphism rings of finite spectra, and by a recent result of Burklund,
   also \(\mathbb{S}/p^2\) for odd primes \(p\) and \(\mathbb{S}/2^3\) provide examples of \(\mathbb{E}_1\)-algebras.
   (I haven't got to read the paper yet, so I can't say how canonical or unique these rings are. These are almost surely not computable anyway.)
5. The filtration is complete in the sense that its limit is \(D_E X\). Caution is due in translating this into computations on homotopy groups.
   We don't plan to cover this part in this blog post.
1. Although \(\Delta^{\textrm{inj}}\) is coinitial in \(\Delta\), the same is not true for \(\Delta_{\leq n}\).
   This is one reason we demanded that \(E\) be \(\mathbb{E}_1\).
   
Another reason for demanding a ring structure lies with the identification of the Adams \(E_2\)-page as \(\mathrm{Ext}\)-groups
of graded comodules over a Hopf algebroid. This also depends on a flatness conditions which will not be discussed.

We'll make use of the following well-known description of the Adam tower [ND, Prop. 2.14]:
#+BEGIN_QUOTE
Let \(I \coloneqq \mathrm{fib}(\mathbb{S} \to E)\) be the "kernel" of the ring's unit. Set iteratively
\[
T^{(-1)}_E X \coloneqq X, T^{(n+1)}_E X \coloneqq T^{(n)}_E X \otimes I \to \mathbb{S} \otimes T^{(n)}_E X.
\]
So that \(T^{(n)}_E X \simeq X \otimes I^{\otimes (1 + n)}\).

Then \(T^{(n)}_E X \to X \to D^{(n)}_E X\) are (a tower of) fiber sequences, where the middle term is the constant tower,
and the lateral terms are the towers described above.
The limit of the tower \(T_E X\) is thus the fiber of the map \(X \to D_E X\).
#+END_QUOTE
Arguably, both the tower \(T^\bullet_E X\) or \(D^\bullet_E X\) deserve the name the Adams tower, although the literature has assigned
the name to the former. We will call \(T^{\color{gray}(n)}_E\) the *fiber of descent* (tower).

* Postnikov convergence
Recall that every spectrum \(X\) is the limit of its Postnikov truncations \(\tau_{\leq m} X\), and the only spectrum which is \(\infty\)-connective
is zero. The following trick is extracted from [TC, Lem. I.2.6]

#+BEGIN_QUOTE
We say that an exact functor \(F : \mathrm{Sp} \to \mathrm{Sp}\) is *bounded below* if there is a constant \(c \in \mathbb{Z}\) such that
\(F\) sends connective spectra to \(c\)-connective spectra.

If \(F\) is bounded below, then \(F(X) \simeq \lim_{m \to \infty} F(\tau_{\leq m} X)\) is the limit of its value on the Postnikov tower.
#+END_QUOTE
Intuitively, this is a condition similar to "finite cohomological dimension" assumptions.

*Proof.* As \(F\) is exact, there are fiber sequences
\[
F(\tau^{\gt m} X) \to F(X) \to F(\tau_{\geq m} X).
\]
We just have to show that the limit \(\lim_{m} F(\tau^{\gt m} X)\) is zero. The assumption implies that each \(F(\tau^{\gt m} X)\) is \((m-c)\)-connective, and
a sequential limit of \(r\)-connective spectra is \((r-1)\)-connective, so the fiber is \(\infty\)-connective.

As evident from the argument, the assumption on \(F\) can be relaxed, and there is a similar generalisation, replacing \(\mathrm{Sp}\) with
stable categories with \(t\)-structure. The interested reader will have already taken this as an exercise.

We verify that the classical descent functors, as well as the \(p\)-completion functor, are bounded below.

#+BEGIN_QUOTE
If \(E\) is a connective \(\mathbb{E}_1\)-ring whose \(\pi_0\) is a quotient or localisation of \(\mathbb{Z}\), then the fiber of descent \(T_E\) and descent \(D_E\)
are bounded below functors.
#+END_QUOTE

*Proof* For a connective ring spectrum \(E\), the fiber \(I\) of the unit morphism is \((-1)\)-connective, and \(\pi_{-1} I\) is the cokernel of \(\mathbb{Z} \to \pi_0 E\).
In the stated case, \((\pi_{-1}I)^{\otimes 2} = 0\), so all the \(I^{\otimes(1+n)}\) are \((-1)\)-connective.
The functor \(T_E\) decreases connectivity by at most \(2\), and is thus bounded below. It follows that the descent object \(D_E\) is also bounded below.

#+BEGIN_QUOTE
The \(p\)-adic completion, which is the Bousfield localisation of spectra at \(\mathbb{S}/p\), is given as a limit as follows:
\[
X_{\hat p} \simeq \lim_{n \to \infty} X/p^n.
\]
As a result, \(p\)-completion decreases connectivity by at most \(1\).
#+END_QUOTE

*Proof* The \(p\)-completion is part of the recollement on \(\mathrm{Sp}\) induced by the idempotent algebra \(\mathbb{S}[1/p]\).
More precisely, let \(C \coloneqq \mathrm{fib}(\mathbb{S} \to \mathbb{S}[1/p])\) be its complementary idempotent coalgebra.

We have (see the previous post on inverting endomorphisms)
\[
\begin{gather*}\mathbb{S}[1/p] \simeq \operatorname*{colim} \left(\mathbb{S} \xrightarrow{p} \mathbb{S} \xrightarrow{p} \ldots\right)\\
C \simeq \operatorname{\Omega} \operatorname*{colim}_n \mathbb{S}/p^n \simeq \operatorname*{colim}_n (\mathbb{S}/p^n)^\vee \eqqcolon \operatorname{\Omega}\mathbb{S}/p^\infty,\end{gather*}
\]
and the \(p\)-completion is given by the mapping spectrum \(X_{\hat p} \simeq \mathrm{map}(\operatorname{\Omega}\mathbb{S}/p^\infty, X)\). The above formula follows.

* The comparison of \(D_E\) with completion
Assume for this section that \(\pi_0 E \simeq \mathbb{Z}/n\). The classical situation is concerned with the discrete ring spectrum \(E = \mathbb{F}_p\), but
everything we said above about idempotent algebras applies to \(\mathbb{S}[1/n]\). We call the \(\mathbb{S}/n\)-localisation \(n\)-(adic )completion.

#+BEGIN_QUOTE
Every \(\mathbb{S}/n\)-acyclic spectrum is \(E\)-acyclic. Thus every \(E\)-local spectrum, in particular every spectrum which admits an \(E\)-module structure, is \(n\)-complete.
#+END_QUOTE
*Proof.* The \(\mathbb{S}/n\)-acyclic spectra are exactly the \(\mathbb{S}[1/n]\)-modules, and \(\mathbb{S}[1/n] \otimes E = 0\).

The \(E\)-locality of \(E\)-modules follows from
\[\mathrm{map}_{\mathrm{Sp}}(X, M) \simeq \mathrm{map}_{\textrm{Mod-}E}(X \otimes E, M)\]

Thus the descent diagram \(D^\bullet_E X\) consists of \(E\)-local spectra, so the
limit \(D_E X\) is also \(E\)-local.
We thus obtain a unique factorisation
\[
X \to X_{\hat n} \to D_E X.
\]

#+BEGIN_QUOTE
If \(E\) and \(X\) are connective, then \(X\to D_E X\) is an \(n\)-adic equivalence. In other words, \(X_{\hat n} \xrightarrow{\sim} D_E X\) is an equivalence.
#+END_QUOTE
*Proof.* As we have seen, both sides are limits of their values on truncations, and the spectra for which the conclusion holds is stable (and idempotent complete).
Thus it suffices to prove the conclusion when \(X\) is discrete (i.e. an Eilenberg--Mac Lane spectrum).
We can tensor the \(E\)-descent diagram with \(\mathbb{S}/n\) (a _finite_ spectrum!), which commutes with totalisation.
The goal is to show that \(X/n \to (D_E X)/n \simeq D_E(X/n)\) is an isomorphism.

We show that \(X/n\) admits an \(E\)-module structure. As \(X\) is discrete,  it admits a \(\mathbb{Z}\)-module structure,
and \(X/n\) admits a module structure over \(\mathbb{Z} \otimes \mathbb{S}/n \simeq \mathbb{Z}/n \simeq \tau_{\leq 0} E\).
Since \(E\) was assumed to be connective, the truncation \(E \to \tau_{\leq 0} E\) is a morphism of rings, and we're done.

* The comparison of \(D_E\) with localisation
Assume now that \(\pi_0 E \simeq \mathbb{Z}[T^{-1}]\), then \(E\) is an algebra over the idempotent algebra of the Moore spectrum \(\mathbb{S}[T^{-1}]\).
Hence there is a factorisation
\[
X \to X[T^{-1}] \to D_E X.
\]
#+BEGIN_QUOTE
If \(E\) and \(X\) are connective, then \(X[T^{-1}] \simeq D_E X\).
#+END_QUOTE
*Proof.* As before, we reduce to the case where \(X\) is discrete. Since \(E \simeq \mathbb{S}[T^{-1}] \otimes E\), we have
\(D_E X \simeq D_E(X[T^{-1}])\). Again, the \(E\)-descent diagram for \(X[T^{-1}]\) splits since it admits a module structure over \(\tau_{\leq 0} E\).
