---
title: "(Central) group extensions from the homotopy perspective"
date: 2025-12-26T09:07:34+01:00
draft: false
math: true
toc: true
tags:
  - Math
  - Algebra
description: "A classical lemma used to construct k-invariants, and its relation to group extensions"
---

\[
  \gdef\Bund{\mathbf{B}}
  \gdef\Aut{\mathrm{Aut}}
  \gdef\fib{\mathrm{fib}}
  \gdef\Ani{\mathrm{An}}
  \gdef\AniB{{\mathrm{An}_\ast}}
  \gdef\Grp{\mathrm{Grp}}
  \gdef\Loop{\mathrm{\Omega}}
\]

The original version was posted on my [[https://toporiame.blogspot.com/2025/08/a-homotopical-revisit-to-non-abelian.html][Blogspot]], followed subsequently
by a more elaborate [[https://www.bananaspace.org/wiki/%E7%94%A8%E6%88%B7:NaCNO/%E5%90%8C%E4%BC%A6%E8%AE%BA%E7%9C%BC%E4%B8%AD%E7%9A%84%E4%B8%AD%E5%BF%83%E6%89%A9%E5%BC%A0][Chinese version]], hosted
on 香蕉空间 Bananaspace, where I reviewed some group theory and
higher algebra for a more clear story. Feel free to make suggestions
and please do point out any other error you notice!

This post tries to explain from a homotopist's perspective the following
statement:

**PROPOSITION.** \(1 \to A \to G \to Q \to 1\) are classified by
(homotopy classes of) maps \(\Bund Q \to \Bund ^2 A.\)

Under the hood of fancy language, this is really an elementary algebraic statement.

* I. Central extensions of groups are classified by \(\mathrm{H}^2(Q,-)\)
:PROPERTIES:
:CUSTOM_ID: I-central-extension-is-H2
:END:

It's a basic result in group theory/group cohomology that the second
cohomology of \(Q\) with coefficients in a trivial module \(A\)
classifies such central extensions. More generally, if \(A\) carries
some \(Q\)-action, the cohomology with twisted coefficients
\(\mathrm{H}^2(Q; A)\) classifies extensions where the conjugation
action of \(Q\) on \(A\) coincides with the given one. The zero class in
\(\mathrm{H}^2(Q; A)\) corresponds to the semi-direct product in either
case.

The usual algebraic proof often consists of directly manipulating
2-cocycles to write down the multiplication rule, a boring and tedious
process that is hardly illuminating. In this blogpost. I hope to shed
some light onto the result by putting on the lenses of homotopy theory.
We shall focus on the case of central extensions. Here we have the
following Lemma 3.4.2 in May-Ponto's More Concise book. With the
point-set mess cleaned up, it says:

*Lemma* Let \(f : X \to Y\) be a be a map of connected pointed spaces
whose ﬁber \(\fib f\) is an Eilenberg-Mac Lane space \(\Bund ^n A\) for
some abelian group \(A\) and \(n \geq 1\). Then the following are
equivalent:
1. The fiber sequence of \(f\) extends one step to the right:
   \[
     \Bund ^n A \to X
                \xrightarrow{f} Y
                \xrightarrow{k} \Bund ^{n+1} A.
   \]
2. The fundamental group \(\pi_1(Y)\) acts trivially
   on \(\pi_n(\fib f) = A\).

In this case, The cohomology class \(k \in \mathrm{H}^{n+1} (Y; A)\)
represented by \(k : Y \to \Bund^{n+1} A\) is the only obstruction to
the lifting of maps \(T \to Y\) along \(f\). These are famously known
under the names of /\(k\)-invariants/ and /characteristic classes/. This
result is of great utility in the theory of Postnikov-Whitehead towers.

If we apply the lemma to the map \(\Bund G \to \Bund Q\) with fiber
\(\Bund A\), the action of \(Q\) on \(A\) referred to above is by
conjugation (see later), so it's exactly the central extensions that are
classified by \(\mathrm{Map}_\Ani (\Bund Q, \Bund ^2A)\). This is a
\(2\)-truncated space with \(\pi_n = \mathrm{H}^{2-n}(Q; A)\).

The proof presented in May-Ponto uses the Serre spectral sequence. In
this blogpost, I'll try to explain the statement within the context of
(higher) group extensions.

* II. The threefold way of group extensions
:PROPERTIES:
:CUSTOM_ID: II-the-threefold-way
:END:
Let's put on out homotopy hat and apply the machinery to (discrete)
groups. We want to describe arbitrary extensions of groups \(1 \to N \to
G \to Q \to 1\) .
** II.1 Group extension? That's just a bundle.
:PROPERTIES:
:CUSTOM_ID: II-1-unstraight
:END:
Famously from classical topology, \(F\)-bundles with structure group
\(G\) are classified by (unpointed) maps into \(\Bund G\), and they're
the same as principal \(G\)-bundles.

*Example* Rank \(n\) vector bundles have structure groups
\(\mathrm{GL}_n\). they are classified by \(\Bund \mathrm{GL}_n\). Due
to reasons of Lie theory, we know this from classical geometry as
\(\mathrm{BO}(n)\) or \(\mathrm{BU}(n)\), depending on the base field.

A direct inspection of the Puppe sequence shows that arbitrary
extensions of groups \(1 \to N \to G \to Q \to 1\) are precisely the
\(\Bund N\)-bundles over \(\Bund Q\). By (un)straightening they are
equivalently given by functors \(\mathrm{Fun}(\Bund Q, \Ani)\) which
land in the full subgroupoid generated by \(\Bund N\). In other words,
the \(N\)-extensions of \(Q\) are classified by \(\Bund \Aut_\Ani (\Bund N)\).

** II.2 The very important /point/: Semi-direct products
:PROPERTIES:
:CUSTOM_ID: II-2-semidirect
:END:
The careless reader (like me) might have remembered that \(Q \to \Aut_\Grp(N)\)
classifies only the semi-direct products!
Why does the similar construction above classify *all* extensions? What's different here?

It took me a while to remember that /semi-direct products are split extensions/.
Under unstraightening, these are bundles *equipped with a distinguished section*.

In other words I've mixed up \(\Aut_\Ani (\Bund N)\) with
\(\Aut_\AniB (\Bund N)\).
1. \(\Aut_\AniB (\Bund N)\) classifies *pointed* bundles, which are exactly the split extensions.
   Observe that it's equivalent to the classifying space \(\Bund \Aut_\Grp(N)\).
2. \(\Aut_\Ani (\Bund N)\) receives a map from the latter through forgetting the
   (datum witnessing the preservation of) basepoint.

These sit in a fiber sequence
\[
  N \to \Aut_\AniB (\Bund N)
    \to \Aut_\Ani(\Bund N)
    \to \Bund N.
\]
Here the last map is evaluation at the base
point of \(\Bund N\). (To see this, use e.g. that \(\AniB \to \Ani\) is
the universal left fibration.)

As the middle map is a group morphism, this sequence extends to the
right into
\[
  \Aut_\Ani (\Bund N) \to \Bund N
                      \to \Bund \Aut_\AniB (\Bund N)
                      \to \Bund \Aut_\Ani (\Bund N),
\]
where the conjugation action of \(N\) on itself inducese the map
\(\Bund N \to \Bund \Aut_\Grp(N) \simeq \Bund \Aut_{\AniB}(\Bund N)\). We see that
\[
  \pi_0\Aut_\Ani(\Bund N) = \mathrm{Out}(N), \pi_1\Aut_\Ani (\Bund N) = Z(N).
\]

If we further assume that \(N = \Bund^n A, n \geq 0\) is (a delooping of) an abelian group,
then the (pointed) map \(\Bund^{n+1} A \to \Bund\Aut_\AniB (\Bund^n A)\)
comes equipped with a nulhomotopy, witnessing a splitting
\[
  \Aut_\Ani (\Bund^n A) \simeq \Aut_\AniB (\Bund^n A) \times \Bund^{n+1} A
                        \simeq \Aut_\Grp(A) \times \Bund^{n+1}A.
\]
I should warn +you+ myself that this splitting is only one of spaces, not of groups.

*Exercise* The map \(\Aut_\Ani (\Bund N) \to \Bund N\) is in general NOT
a morphism of groups.

As an irrelevant side note, the extension \(1 \to G/Z(G) \to \Aut (G)
\to \mathrm{Out}(G) \to 1\) doesn't always split for (non-abelian)
groups.

** II.3 Another attempt at central extensions
:PROPERTIES:
:CUSTOM_ID: II-3-brave-new-cext
:END:
Take now the group \(A\) to be discrete abelian, then the space \(\Bund
A\) is canonically a commutative group, as well as all its higher
deloopings \(\Bund^n A\). Its action on itself by translation provides a
group morphism
\[
  \Bund^n A \xrightarrow{\lambda} \Aut_\Ani (\Bund^n A).
\]
Moreover, the \(\Bund ^n A\)-bundle classified by the delooping
\[
  \Bund^{n+1} A\xrightarrow{\Bund\lambda} \Bund\Aut_\Ani (\Bund^n A)
\]
is exactly the path fibration \(\mathbf{E}\Bund^n A \to \Bund^{n+1} A\),
a.k.a the action (\(\infty\)-)groupoid of the group \(\Bund^n A\). This
is a classical construction of delooping, known as the bar construction.

We now really make use of \(A\) being /DISCRETE ABELIAN/. I claim that
the morphism \(\Bund\lambda\) exhibits \(\Bund^{n+1} A\) as an
\((n+1)\)-connective cover of \(\Bund \Aut_\Ani (\Bund^n A)\).

To see this, observe the following pullback square.
\[\begin{CD}
  \bullet @>>> \mathrm{pt}\\
  @VVV @VVV\\
  \mathbf{E}\Bund^n A @>>>
  \Bund\Aut_\AniB(\Bund^n A)\\
  @VVV @VVV\\
  \Bund^{n+1} A @>>> \Bund\Aut_\Ani (\Bund^n A)
\end{CD}\]
The top left corner \(\bullet\) is the fiber of \(\Bund \lambda\). Seeing as
\(\mathbf{E}\Bund^nA\) is contractible, it's also equivalent to
\(\Loop \Bund \Aut _\AniB(\Bund^n A)= \Aut _\AniB(\Bund^n A)\).
Because \(\Bund^n A\) is Eilenberg-Mac Lane, this is just the discrete group \(\Aut_\Grp(A)\).

This shows that the map \(\Bund\lambda\) is a map with discrete fiber
mapping out of a simply connected space into a connected space. This
means that it is a universal cover, and hence the fiber of the
\(1\)-truncation map
\[
  \Bund\Aut_\Ani (\Bund^n A) \to \tau_{\leq1} \Bund\Aut_\Ani (\Bund^n A).
\]
The latter can be identified as \(\Bund\Aut _\Grp(N)\), and it classifies the
action of fundamental groups on the fibers. (*EXERCISE!*)

From this discussion, we have obtained the fiber sequence we're looking
for
\[
  \Aut_\Grp (A) \to \Bund^{n+1} A
                \to \Bund\Aut_\Ani (\Bund ^n A)
                \to \Bund\Aut_\Grp (A).
\]
and a non-computational proof of the Lemma 3.4.2 presented at the start.

As a special case in \(n = 1\): Given an extension \(1 \to A \to G \to Q
\to 1\) with abelian kernel and classifying map \(g : \Bund Q \to
\Bund\Aut_\Ani (\Bund A)\), a witness to the triviality of the
\(Q\)-module \(A\) is exactly a lift of \(g\) to \(\Bund^2 A\).

* III. Another well-known example
:PROPERTIES:
:CUSTOM_ID: III-PGL
:END:
The theory of classifying objects work in a more general context. Most
notably for (sheaf) topoi. (I'm not too confident on the details, but
this seems to be what's going on in principle. PLEASE DO CORRECT ME, I
VERY WELL MAY BE WRONG)

In particular, we have a central extension of group sheaves on affine
schemes (with your favorite topology):
\[
  1 \to \mathbb{G}_m \to \mathrm{GL}_n \to \mathrm{PGL}_n \to 1,
\]
These should correspond to fiber sequences
\[
  \Bund \mathbb{G}_m \to \Bund \mathrm{GL}_n
                     \to \Bund\mathrm{PGL}_n
                     \to \Bund ^2\mathbb{G}_m
\]
giving corresponding long exact sequences on cohomology (=global sections).

* A. Further links and miscellany
:PROPERTIES:
:CUSTOM_ID: A-reading-list
:END:
1. [[https://ncatlab.org/nlab/show/infinity-group+extension][nLab page on \(\infty\)-group extension]]
2. [[https://www.davidjaz.com/Talks/DJM_HoTT2020.pdf][David Jaz Myers: Higher Schreier Theory]]
3. [[https://arxiv.org/abs/2405.12118][Georg Lehner: Group completion via the action \(\infty\)-category. Contains juicy stuff about groups]]
4. [[https://drive.google.com/file/d/1-64jIWOXvSD2apMwYDe1LRS74IXpb-E6][May-Ponto's "More Concise" book. Grabbed from Ranicki's website, TOC added by me.]]

** i. Very much classical geometry
:PROPERTIES:
:CUSTOM_ID: A-1-principal
:END:
The space \(\Bund G\) really classifies *principal \(G\)-bundles*. With
the datum of a \(G\)-action on \(F\), these induce \(F\)-bundles as follows:
\[\begin{array}{rcl}
  (B \xrightarrow{f} \Bund G) &\simeq &(P = f^\ast \mathbf{E}G \to B : \text{principal bundle})\\
                              &\simeq &(P \times_G F \to B : \text{\(F\)-bundle with\(G\)-structure})
\end{array}\]

** ii. The homotopy action of \(\pi_1(Y)\) on \(F := \operatorname{fib} (X \to Y)\) (May-Ponto 1.4-1.5)
:PROPERTIES:
:CUSTOM_ID: A-2-pi1-action
:END:
In the sections May-Ponto 1.4-1.5, the authors defined for connected
pointed spaces \(X\) and \(Y\) an action of the fundamental group
\(\pi_1(Y)\) on \(\pi_0\mathrm{Map}_\AniB (X,Y)\). Upon inspection of
the geometric definition, this should arise from an \(S^1\)-comodule
structure on \(X\) by "extruding a neighborhood around the basepoint".
This is where the conjugation action comes from. There's quite some
potential confusion chasing the basepoint around.

There's another action on the fiber given heuristically by path concatenation.
With the following description of the fiber
\[
  F = X \times_Y 1 = \big\{(x : X, \alpha : y_0 = f(x)\big\},
\]
we can describe this action as
\[\begin{align*}
  F \times \Loop Y &= X \times_Y 1 \times 1 \times_Y 1 \\
                   &= X \times_Y 1 \times_Y 1 \\ &\xrightarrow{y_0} X \times_Y Y \times_Y 1 \\
                   &= X \times_Y 1 \\
                   &= F,\\
 \left(\left(x : X,\alpha : y_0 = f\left(x\right)\right), \beta : y_0 = y_0\right)
                   &\mapsto\left(x : X, \alpha \circ \beta : y_0 = f\left(x\right)\right).
\end{align*}\]
One can also view this as given by the straightening \(Y \to \Ani, y \mapsto X \times_Y \{y\}\),
plus the equivalence \(Y \simeq \Bund \Loop Y\) determined by a basepoint.
At first glance, this looks much like a right translation rather than
conjugation. Moreover, this map has no reason to preserve basepoints.
(One should think about how these two actions relate to each other.)

* Z. Changelog and TODO

TODO: Rework the appendix on \(\pi_1\)-actions.

Update 2.0 (26.dec.2025): Ported to hugo & org-mode

Update 1.3 (15.aug.2025): Reworked section III completely with a (nice
and) non-sketchy proof.

Update 1.2e (14.aug.2025): Fatal error found and hotfixed.

Update 1.2 (13.aug.2025): Rewording and grammatical fixes, reorganized
MathJax code.
